# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65livery.proto\x12\x08\x64\x65livery\"4\n\x17\x44riverAssignmentRequest\x12\x19\n\x11\x61ssigned_order_id\x18\x01 \x01(\t\"Q\n\x1b\x44\x65liveryStatusUpdateRequest\x12\x19\n\x11\x61ssigned_order_id\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65livery_status\x18\x02 \x01(\t\"P\n\x18\x44riverAssignmentResponse\x12\x1a\n\x12\x61ssigned_driver_id\x18\x01 \x01(\t\x12\x18\n\x10\x61ssigned_vehicle\x18\x02 \x01(\t\"9\n\x1c\x44\x65liveryStatusUpdateResponse\x12\x19\n\x11update_successful\x18\x01 \x01(\x08\"2\n\x15\x44\x65liveryStatusRequest\x12\x19\n\x11\x61ssigned_order_id\x18\x01 \x01(\t\"L\n\x16\x44\x65liveryStatusResponse\x12\x19\n\x11\x61ssigned_order_id\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65livery_status\x18\x02 \x01(\t\"\"\n\rDriverRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\"F\n\x18\x44riverDeliveriesResponse\x12*\n\ndeliveries\x18\x01 \x03(\x0b\x32\x16.delivery.DeliveryInfo\"6\n\x0c\x44\x65liveryInfo\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0corder_status\x18\x02 \x01(\t2\xed\x02\n\x0f\x44\x65liveryService\x12U\n\x0c\x41ssignDriver\x12!.delivery.DriverAssignmentRequest\x1a\".delivery.DriverAssignmentResponse\x12]\n\x0cUpdateStatus\x12%.delivery.DeliveryStatusUpdateRequest\x1a&.delivery.DeliveryStatusUpdateResponse\x12N\n\tGetStatus\x12\x1f.delivery.DeliveryStatusRequest\x1a .delivery.DeliveryStatusResponse\x12T\n\x15GetAssignedDeliveries\x12\x17.delivery.DriverRequest\x1a\".delivery.DriverDeliveriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVERASSIGNMENTREQUEST']._serialized_start=28
  _globals['_DRIVERASSIGNMENTREQUEST']._serialized_end=80
  _globals['_DELIVERYSTATUSUPDATEREQUEST']._serialized_start=82
  _globals['_DELIVERYSTATUSUPDATEREQUEST']._serialized_end=163
  _globals['_DRIVERASSIGNMENTRESPONSE']._serialized_start=165
  _globals['_DRIVERASSIGNMENTRESPONSE']._serialized_end=245
  _globals['_DELIVERYSTATUSUPDATERESPONSE']._serialized_start=247
  _globals['_DELIVERYSTATUSUPDATERESPONSE']._serialized_end=304
  _globals['_DELIVERYSTATUSREQUEST']._serialized_start=306
  _globals['_DELIVERYSTATUSREQUEST']._serialized_end=356
  _globals['_DELIVERYSTATUSRESPONSE']._serialized_start=358
  _globals['_DELIVERYSTATUSRESPONSE']._serialized_end=434
  _globals['_DRIVERREQUEST']._serialized_start=436
  _globals['_DRIVERREQUEST']._serialized_end=470
  _globals['_DRIVERDELIVERIESRESPONSE']._serialized_start=472
  _globals['_DRIVERDELIVERIESRESPONSE']._serialized_end=542
  _globals['_DELIVERYINFO']._serialized_start=544
  _globals['_DELIVERYINFO']._serialized_end=598
  _globals['_DELIVERYSERVICE']._serialized_start=601
  _globals['_DELIVERYSERVICE']._serialized_end=966
# @@protoc_insertion_point(module_scope)
