# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import delivery_pb2 as delivery__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in delivery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeliveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignDriver = channel.unary_unary(
                '/delivery.DeliveryService/AssignDriver',
                request_serializer=delivery__pb2.DriverAssignmentRequest.SerializeToString,
                response_deserializer=delivery__pb2.DriverAssignmentResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/delivery.DeliveryService/UpdateStatus',
                request_serializer=delivery__pb2.DeliveryStatusUpdateRequest.SerializeToString,
                response_deserializer=delivery__pb2.DeliveryStatusUpdateResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/delivery.DeliveryService/GetStatus',
                request_serializer=delivery__pb2.DeliveryStatusRequest.SerializeToString,
                response_deserializer=delivery__pb2.DeliveryStatusResponse.FromString,
                _registered_method=True)
        self.GetAssignedDeliveries = channel.unary_unary(
                '/delivery.DeliveryService/GetAssignedDeliveries',
                request_serializer=delivery__pb2.DriverRequest.SerializeToString,
                response_deserializer=delivery__pb2.DriverDeliveriesResponse.FromString,
                _registered_method=True)


class DeliveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AssignDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssignedDeliveries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeliveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignDriver,
                    request_deserializer=delivery__pb2.DriverAssignmentRequest.FromString,
                    response_serializer=delivery__pb2.DriverAssignmentResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=delivery__pb2.DeliveryStatusUpdateRequest.FromString,
                    response_serializer=delivery__pb2.DeliveryStatusUpdateResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=delivery__pb2.DeliveryStatusRequest.FromString,
                    response_serializer=delivery__pb2.DeliveryStatusResponse.SerializeToString,
            ),
            'GetAssignedDeliveries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignedDeliveries,
                    request_deserializer=delivery__pb2.DriverRequest.FromString,
                    response_serializer=delivery__pb2.DriverDeliveriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'delivery.DeliveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('delivery.DeliveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeliveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AssignDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery.DeliveryService/AssignDriver',
            delivery__pb2.DriverAssignmentRequest.SerializeToString,
            delivery__pb2.DriverAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery.DeliveryService/UpdateStatus',
            delivery__pb2.DeliveryStatusUpdateRequest.SerializeToString,
            delivery__pb2.DeliveryStatusUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery.DeliveryService/GetStatus',
            delivery__pb2.DeliveryStatusRequest.SerializeToString,
            delivery__pb2.DeliveryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssignedDeliveries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery.DeliveryService/GetAssignedDeliveries',
            delivery__pb2.DriverRequest.SerializeToString,
            delivery__pb2.DriverDeliveriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
