# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"b\n\x10MakeOrderRequest\x12\x10\n\x08\x62uyer_id\x18\x01 \x01(\t\x12\x11\n\tvendor_id\x18\x02 \x01(\t\x12)\n\rordered_items\x18\x03 \x03(\x0b\x32\x12.order.OrderedItem\"2\n\x15GetOrderStatusRequest\x12\x19\n\x11tracking_order_id\x18\x01 \x01(\t\"H\n\x13UpdatedOrderRequest\x12\x19\n\x11tracking_order_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63urrent_status\x18\x02 \x01(\t\"R\n\x11MakeOrderResponse\x12\x1a\n\x12generated_order_id\x18\x01 \x01(\t\x12!\n\x19order_confirmation_status\x18\x02 \x01(\t\"R\n\x16GetOrderStatusResponse\x12\x19\n\x11tracking_order_id\x18\x01 \x01(\t\x12\x1d\n\x15order_progress_status\x18\x02 \x01(\t\"H\n\x14UpdatedOrderResponse\x12\x19\n\x11tracking_order_id\x18\x01 \x01(\t\x12\x15\n\rlatest_status\x18\x02 \x01(\t\"T\n\x0bOrderedItem\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x18\n\x10product_quantity\x18\x02 \x01(\x05\x12\x15\n\rproduct_price\x18\x03 \x01(\x02\".\n\x1a\x43heckOrderIsPresentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"6\n\x1b\x43heckOrderIsPresentResponse\x12\x17\n\x0forder_isPresent\x18\x01 \x01(\x08\x32\xca\x02\n\x0cOrderService\x12>\n\tMakeOrder\x12\x17.order.MakeOrderRequest\x1a\x18.order.MakeOrderResponse\x12M\n\x12UpdatedOrderStatus\x12\x1a.order.UpdatedOrderRequest\x1a\x1b.order.UpdatedOrderResponse\x12M\n\x0eGetOrderStatus\x12\x1c.order.GetOrderStatusRequest\x1a\x1d.order.GetOrderStatusResponse\x12\\\n\x13\x43heckOrderIsPresent\x12!.order.CheckOrderIsPresentRequest\x1a\".order.CheckOrderIsPresentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAKEORDERREQUEST']._serialized_start=22
  _globals['_MAKEORDERREQUEST']._serialized_end=120
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=122
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=172
  _globals['_UPDATEDORDERREQUEST']._serialized_start=174
  _globals['_UPDATEDORDERREQUEST']._serialized_end=246
  _globals['_MAKEORDERRESPONSE']._serialized_start=248
  _globals['_MAKEORDERRESPONSE']._serialized_end=330
  _globals['_GETORDERSTATUSRESPONSE']._serialized_start=332
  _globals['_GETORDERSTATUSRESPONSE']._serialized_end=414
  _globals['_UPDATEDORDERRESPONSE']._serialized_start=416
  _globals['_UPDATEDORDERRESPONSE']._serialized_end=488
  _globals['_ORDEREDITEM']._serialized_start=490
  _globals['_ORDEREDITEM']._serialized_end=574
  _globals['_CHECKORDERISPRESENTREQUEST']._serialized_start=576
  _globals['_CHECKORDERISPRESENTREQUEST']._serialized_end=622
  _globals['_CHECKORDERISPRESENTRESPONSE']._serialized_start=624
  _globals['_CHECKORDERISPRESENTRESPONSE']._serialized_end=678
  _globals['_ORDERSERVICE']._serialized_start=681
  _globals['_ORDERSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
