# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeOrder = channel.unary_unary(
                '/order.OrderService/MakeOrder',
                request_serializer=order__pb2.MakeOrderRequest.SerializeToString,
                response_deserializer=order__pb2.MakeOrderResponse.FromString,
                _registered_method=True)
        self.UpdatedOrderStatus = channel.unary_unary(
                '/order.OrderService/UpdatedOrderStatus',
                request_serializer=order__pb2.UpdatedOrderRequest.SerializeToString,
                response_deserializer=order__pb2.UpdatedOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/order.OrderService/GetOrderStatus',
                request_serializer=order__pb2.GetOrderStatusRequest.SerializeToString,
                response_deserializer=order__pb2.GetOrderStatusResponse.FromString,
                _registered_method=True)
        self.CheckOrderIsPresent = channel.unary_unary(
                '/order.OrderService/CheckOrderIsPresent',
                request_serializer=order__pb2.CheckOrderIsPresentRequest.SerializeToString,
                response_deserializer=order__pb2.CheckOrderIsPresentResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatedOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOrderIsPresent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeOrder,
                    request_deserializer=order__pb2.MakeOrderRequest.FromString,
                    response_serializer=order__pb2.MakeOrderResponse.SerializeToString,
            ),
            'UpdatedOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatedOrderStatus,
                    request_deserializer=order__pb2.UpdatedOrderRequest.FromString,
                    response_serializer=order__pb2.UpdatedOrderResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=order__pb2.GetOrderStatusRequest.FromString,
                    response_serializer=order__pb2.GetOrderStatusResponse.SerializeToString,
            ),
            'CheckOrderIsPresent': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrderIsPresent,
                    request_deserializer=order__pb2.CheckOrderIsPresentRequest.FromString,
                    response_serializer=order__pb2.CheckOrderIsPresentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/MakeOrder',
            order__pb2.MakeOrderRequest.SerializeToString,
            order__pb2.MakeOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatedOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/UpdatedOrderStatus',
            order__pb2.UpdatedOrderRequest.SerializeToString,
            order__pb2.UpdatedOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/GetOrderStatus',
            order__pb2.GetOrderStatusRequest.SerializeToString,
            order__pb2.GetOrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOrderIsPresent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/CheckOrderIsPresent',
            order__pb2.CheckOrderIsPresentRequest.SerializeToString,
            order__pb2.CheckOrderIsPresentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
