# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\x83\x01\n\x15ProcessPaymentRequest\x12\x10\n\x08payer_id\x18\x01 \x01(\t\x12\x1b\n\x13\x61ssociated_order_id\x18\x02 \x01(\t\x12\x1a\n\x12transaction_amount\x18\x03 \x01(\x02\x12\x1f\n\x17selected_payment_method\x18\x04 \x01(\t\"V\n\x16ProcessPaymentResponse\x12\x1a\n\x12payment_successful\x18\x01 \x01(\x08\x12 \n\x18generated_transaction_id\x18\x02 \x01(\t\"+\n\x17GetPaymentStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"J\n\x18GetPaymentStatusResponse\x12\x16\n\x0epayment_status\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t2\xbc\x01\n\x0ePaymentService\x12Q\n\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12W\n\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSPAYMENTREQUEST']._serialized_start=27
  _globals['_PROCESSPAYMENTREQUEST']._serialized_end=158
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_start=160
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_end=246
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_start=248
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_end=291
  _globals['_GETPAYMENTSTATUSRESPONSE']._serialized_start=293
  _globals['_GETPAYMENTSTATUSRESPONSE']._serialized_end=367
  _globals['_PAYMENTSERVICE']._serialized_start=370
  _globals['_PAYMENTSERVICE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
