# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import restaurant_pb2 as restaurant__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in restaurant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRestaurantsMenu = channel.unary_unary(
                '/restaurant.RestaurantService/GetRestaurantsMenu',
                request_serializer=restaurant__pb2.RestaurantMenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantMenuResponse.FromString,
                _registered_method=True)
        self.UpdateRestaurantsMenu = channel.unary_unary(
                '/restaurant.RestaurantService/UpdateRestaurantsMenu',
                request_serializer=restaurant__pb2.UpdateRestaurantMenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.UpdateRestaurantMenuResponse.FromString,
                _registered_method=True)
        self.OrderAcceptanceStatus = channel.unary_unary(
                '/restaurant.RestaurantService/OrderAcceptanceStatus',
                request_serializer=restaurant__pb2.OrderDecisionStatusRequest.SerializeToString,
                response_deserializer=restaurant__pb2.OrderDecisionStatusResponse.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRestaurantsMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRestaurantsMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderAcceptanceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRestaurantsMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestaurantsMenu,
                    request_deserializer=restaurant__pb2.RestaurantMenuRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantMenuResponse.SerializeToString,
            ),
            'UpdateRestaurantsMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRestaurantsMenu,
                    request_deserializer=restaurant__pb2.UpdateRestaurantMenuRequest.FromString,
                    response_serializer=restaurant__pb2.UpdateRestaurantMenuResponse.SerializeToString,
            ),
            'OrderAcceptanceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderAcceptanceStatus,
                    request_deserializer=restaurant__pb2.OrderDecisionStatusRequest.FromString,
                    response_serializer=restaurant__pb2.OrderDecisionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRestaurantsMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetRestaurantsMenu',
            restaurant__pb2.RestaurantMenuRequest.SerializeToString,
            restaurant__pb2.RestaurantMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRestaurantsMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/UpdateRestaurantsMenu',
            restaurant__pb2.UpdateRestaurantMenuRequest.SerializeToString,
            restaurant__pb2.UpdateRestaurantMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderAcceptanceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/OrderAcceptanceStatus',
            restaurant__pb2.OrderDecisionStatusRequest.SerializeToString,
            restaurant__pb2.OrderDecisionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
