# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'restaurant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\x12\nrestaurant\"5\n\x15RestaurantMenuRequest\x12\x1c\n\x14restaurant_unique_id\x18\x01 \x01(\t\"p\n\x1bUpdateRestaurantMenuRequest\x12\x1c\n\x14restaurant_unique_id\x18\x01 \x01(\t\x12\x33\n\x12updated_menu_items\x18\x02 \x03(\x0b\x32\x17.restaurant.MenuListing\"L\n\x1aOrderDecisionStatusRequest\x12\x19\n\x11order_tracking_id\x18\x01 \x01(\t\x12\x13\n\x0bis_accepted\x18\x02 \x01(\x08\"m\n\x16RestaurantMenuResponse\x12\x1c\n\x14restaurant_unique_id\x18\x01 \x01(\t\x12\x35\n\x14\x61vailable_menu_items\x18\x02 \x03(\x0b\x32\x17.restaurant.MenuListing\"9\n\x1cUpdateRestaurantMenuResponse\x12\x19\n\x11update_successful\x18\x01 \x01(\x08\"9\n\x1bOrderDecisionStatusResponse\x12\x1a\n\x12\x64\x65\x63ision_confirmed\x18\x01 \x01(\x08\"N\n\x0bMenuListing\x12\x11\n\tdish_name\x18\x01 \x01(\t\x12\x18\n\x10\x64ish_description\x18\x02 \x01(\t\x12\x12\n\ndish_price\x18\x03 \x01(\x02\x32\xc6\x02\n\x11RestaurantService\x12[\n\x12GetRestaurantsMenu\x12!.restaurant.RestaurantMenuRequest\x1a\".restaurant.RestaurantMenuResponse\x12j\n\x15UpdateRestaurantsMenu\x12\'.restaurant.UpdateRestaurantMenuRequest\x1a(.restaurant.UpdateRestaurantMenuResponse\x12h\n\x15OrderAcceptanceStatus\x12&.restaurant.OrderDecisionStatusRequest\x1a\'.restaurant.OrderDecisionStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESTAURANTMENUREQUEST']._serialized_start=32
  _globals['_RESTAURANTMENUREQUEST']._serialized_end=85
  _globals['_UPDATERESTAURANTMENUREQUEST']._serialized_start=87
  _globals['_UPDATERESTAURANTMENUREQUEST']._serialized_end=199
  _globals['_ORDERDECISIONSTATUSREQUEST']._serialized_start=201
  _globals['_ORDERDECISIONSTATUSREQUEST']._serialized_end=277
  _globals['_RESTAURANTMENURESPONSE']._serialized_start=279
  _globals['_RESTAURANTMENURESPONSE']._serialized_end=388
  _globals['_UPDATERESTAURANTMENURESPONSE']._serialized_start=390
  _globals['_UPDATERESTAURANTMENURESPONSE']._serialized_end=447
  _globals['_ORDERDECISIONSTATUSRESPONSE']._serialized_start=449
  _globals['_ORDERDECISIONSTATUSRESPONSE']._serialized_end=506
  _globals['_MENULISTING']._serialized_start=508
  _globals['_MENULISTING']._serialized_end=586
  _globals['_RESTAURANTSERVICE']._serialized_start=589
  _globals['_RESTAURANTSERVICE']._serialized_end=915
# @@protoc_insertion_point(module_scope)
