apiVersion: v1
kind: Service
metadata:
  name: fastapi-bonus
  labels:
    app: fastapi-bonus
spec:
  selector:
    app: fastapi-bonus
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30000
    protocol: TCP